name: my_apps
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  smooth_page_indicator: ^1.0.0+2
  google_sign_in: ^6.2.2
  get: ^4.3.8
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.0.0+1
  sembast: ^3.0.0
  path: ^1.8.0
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  firebase_storage: ^12.1.1
  firebase_messaging: ^15.0.3
  cloud_firestore: ^5.0.2
  collection: ^1.15.0
  http_parser: ^4.0.1
  image_picker: ^1.1.2
  intl: ^0.19.0
  js: ^0.7.1
  meta: ^1.7.0
  test_api: ^0.7.0
  vm_service: ^14.2.1
  leak_tracker: ^10.0.4
  leak_tracker_flutter_testing: ^3.0.3
  material_color_utilities: 0.11.1
  url_launcher: ^6.1.2
  cupertino_icons: ^1.0.5
  flutter_svg: ^2.0.10+1
  font_awesome_flutter: ^10.2.1
  percent_indicator: ^4.2.2
  firebase_database: ^11.1.4
  flutter_signin_button: ^2.0.0

dependency_overrides:
  font_awesome_flutter: ^10.2.1
  firebase_core_platform_interface: ^5.1.0
  firebase_auth_platform_interface: ^7.4.1
  cloud_firestore_platform_interface: ^6.2.8
  firebase_core_web: ^2.17.2
  firebase_auth_web: ^5.12.3
  image_picker_for_web: ^3.0.4
  _flutterfire_internals: ^1.3.38


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/SpaghettiBolognese.jpeg
    - assets/FettuccineAlfredo.jpeg
    - assets/MacNCheese.jpeg
    - assets/SpaghettiAglioOlio.jpeg
    - assets/PenneArrabiata.jpeg
    - assets/Ravioli.jpeg
    - assets/Carbonara.jpeg
    - assets/Tortellini.jpeg
    - assets/food.jpeg
    - assets/burger.jpeg
    - assets/pasta.jpeg
    - assets/pizza.jpeg
    - assets/salade.jpeg
    - assets/sushi.jpeg
    - assets/desserts.jpeg
    - assets/drinks.jpeg
    - assets/pizza_offers.jpeg
    - assets/Salade_offer.jpeg
    - assets/logo.jpeg
    - assets/poster1.jpeg
    - assets/poster2.jpeg
    - assets/poster3.jpeg
    - assets/poster4.jpeg
    - assets/poster5.jpeg
    - assets/Margerita.jpeg
    - assets/Hawaiian Pizza.jpeg
    - assets/meatLovers.jpeg
    - assets/Veggie.jpeg
    - assets/BBQChicken.jpeg
    - assets/QuattroFormaggi.jpeg
    - assets/ShrimpScampi.jpeg
    - assets/WhitePizza.jpeg
    - assets/Mediterranean.jpeg
    - assets/SpicyItalian.jpeg
    - assets/ClassicCheeseburger.jpeg
    - assets/BaconBBQBurger.jpeg
    - assets/MushroomSwissBurger.jpeg
    - assets/SpicyTexanBurger.jpeg
    - assets/VeggieBurger.jpeg
    - assets/GreekFetaBurgers.jpeg
    - assets/ItalianBurger.jpeg
    - assets/KoreanBBQBurger.jpeg
    - assets/MexicanBurger.jpeg
    - assets/PortobelloMushroomBurger.jpeg
    - assets/CaesarSalad.jpeg
    - assets/GreekSalad.jpeg
    - assets/SpinachSalad.jpeg
    - assets/ChickenSalad.jpeg
    - assets/TunaSalad.jpeg
    - assets/dessertOffer.jpeg
    - assets/Tiramisu.jpeg
    - assets/Cheesecake.jpeg
    - assets/ChocolateLavaCake.jpeg
    - assets/Cannoli.jpeg
    - assets/PannaCotta.jpeg
    - assets/Gelato.jpeg
    - assets/FruitTart.jpeg
    - assets/CremeBrulee.jpeg
    - assets/SoftDrinks.jpeg
    - assets/FreshJuice.jpeg
    - assets/IcedTea.jpeg
    - assets/Coffee.jpeg
    - assets/HotChocolate.jpeg
    - assets/Milkshakes.jpeg
    - assets/Smoothies.jpeg
    - assets/FreshLemonade.jpeg
    - assets/American Express.jpeg
    - assets/masterCard.jpeg
    - assets/maestro.jpeg
    - assets/visa.jpeg
    - assets/discover.jpeg
    - assets/splash.gif
    - assets/google_logo.png
  fonts:
    - family: Noto-Sans
      fonts:
        - asset: assets/fonts/NotoSans-VariableFont_wdth,wght.ttf
          weight: 700
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Italic-VariableFont_wght.ttf

    - family: Arial
      fonts:
        - asset: assets/fonts/arial-font/arial.ttf
    - family: DancingScript
      fonts:
        - asset: assets/fonts/DancingScript-VariableFont_wght.ttf