// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOhDz0pjxbxSApCrLSWGdKRC1yRF-wGNE',
    appId: '1:1079532801319:android:2d17ec10e28124948ced02',
    messagingSenderId: '1079532801319',
    projectId: 'cloudkitchen-92d6e',
    storageBucket: 'cloudkitchen-92d6e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZGwxTHGmCPsU57J0j0cQ1h4fkxE83S4c',
    appId: '1:1079532801319:ios:3d4364f82213073c8ced02',
    messagingSenderId: '1079532801319',
    projectId: 'cloudkitchen-92d6e',
    storageBucket: 'cloudkitchen-92d6e.appspot.com',
    iosBundleId: 'com.example.myApps',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqqadm0iVKAKFu8el9winQamlVtRVQCBg',
    appId: '1:1079532801319:web:929f973ddc182e928ced02',
    messagingSenderId: '1079532801319',
    projectId: 'cloudkitchen-92d6e',
    authDomain: 'cloudkitchen-92d6e.firebaseapp.com',
    storageBucket: 'cloudkitchen-92d6e.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZGwxTHGmCPsU57J0j0cQ1h4fkxE83S4c',
    appId: '1:1079532801319:ios:3d4364f82213073c8ced02',
    messagingSenderId: '1079532801319',
    projectId: 'cloudkitchen-92d6e',
    storageBucket: 'cloudkitchen-92d6e.appspot.com',
    iosBundleId: 'com.example.myApps',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqqadm0iVKAKFu8el9winQamlVtRVQCBg',
    appId: '1:1079532801319:web:e1566927ce0027518ced02',
    messagingSenderId: '1079532801319',
    projectId: 'cloudkitchen-92d6e',
    authDomain: 'cloudkitchen-92d6e.firebaseapp.com',
    storageBucket: 'cloudkitchen-92d6e.appspot.com',
  );

}